spring:
  application:
    name: bbriji-manage

server:
  port: 3333
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/

feign:
  hystrix:
    enabled: true # hystrix默认是关闭状态