spring:
  application:
    name: bbriji-website

server:
  port: 2222
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/,http://localhost:1113/eureka/

